version: "3"

services:
  gocity:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      CITY_API_ADDR: gocity
      CITY_API_PORT: 8080
      CITY_API_DB_URL: gocity.hponthieu.com
      CITY_API_DB_USER: gocity
      CITY_API_DB_PWD: gocity-pwd


  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gocity
      POSTGRES_PASSWORD: gocity-pwd
      POSTGRES_DB: gocity
    ports:
      - "5432:5432"
