name: Go CI

on:
  push:
    branches:
      - 'main'

jobs:
  lint:
    name: Lint Go project
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: v1.56.0

  build:
    name: Build Go project
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22'
          cache: false
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/city-api:latest
  
